name: flask_pipeline

on:
    push:
        branches:
            - main

jobs: 
    python_app:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setting up Python in your runner
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'

            - name: Installing dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Running the Flask Application
              run: |
                python app.py &
                sleep 10

            - name: Setting up test cases
              run: |
                echo "Testing has been started."
                curl http://127.0.0.1:5000
                echo "Testing has been completed."
              
